FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY flag-admin-api/target/*.jar app.jar
EXPOSE 8080

ENV DB_HOST=dev_postgres \
    DB_PORT=5432 \
    DB_USERNAME=postgres \
    DB_PASSWORD=postgres \
    REDIS_HOST=dev_redis \
    REDIS_PORT=6379 \
    HOST_IP=192.168.5.66 \
    LOG_LEVEL=INFO \
    JPA_SHOW_SQL=false

ENTRYPOINT ["java", "-jar", "app.jar"]